
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'boilerplate-db'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: